version: '3'

services:
  observatory:
    image: observatory:latest
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/disks:/dev/disks
      - /sys/class/net:/sys/class/net
    ports:
      - "8080:8080"